In [1]:
import  json
import requests
import pandas as pd
import numpy as np
import os,shutil

## code to break out law type in map

In [2]:
f = open("map.txt", "r")
content = f.read()
content

"1 -> Administrative Law\n2 -> Admiralty\n3 -> Agriculture\n4 -> Antitrust &amp; Trade Regulation\n5 -> Attorney's Fees\n6 -> Banking Law\n7 -> Bankruptcy Law\n8 -> Civil Procedure\n9 -> Civil Rights\n10 -> Class Actions\n11 -> Commercial Law\n12 -> Communications Law\n13 -> Constitutional Law\n14 -> Construction\n15 -> Consumer Protection Law\n16 -> Contracts\n17 -> Corp. Governance\n18 -> Corporation &amp; Enterprise Law\n19 -> Criminal Law &amp; Procedure\n20 -> Habeas Corpus\n21 -> Sentencing\n22 -> Cyberspace Law\n23 -> Debt Collection\n24 -> Dispute Resolution &amp; Arbitration\n25 -> Drugs &amp; Biotech\n31 -> ERISA\n26 -> Education Law\n27 -> Elder Law\n28 -> Elections\n29 -> Entertainment Law\n30 -> Environmental Law\n32 -> Ethics &amp; Disciplinary Code\n33 -> Ethics &amp; Professional Responsibility\n34 -> Evidence\n35 -> False Advertising\n36 -> Family Law\n37 -> Gaming Law\n38 -> Government Benefits\n39 -> Government Contracts\n40 -> Government Law\n41 -> Health Law\n42 -> Immigration Law\n43 -> Indian Law\n44 -> Injury &amp; Tort Law\n45 -> Insurance Law\n47 -> Copyright\n49 -> Trade Dress\n50 -> Trade Secrets\n51 -> Trademark\n52 -> International Law\n53 -> International Trade\n54 -> Judgment Enforcement\n55 -> Judges &amp; Judiciary\n56 -> Juvenile Law\n57 -> Labor &amp; Employment Law\n58 -> Landlord Tenant Law\n59 -> Legal Malpractice\n60 -> M&amp;A\n61 -> Media Law\n62 -> Military Law\n63 -> Oil and Gas Law\n64 -> Probate, Trusts &amp; Estates\n65 -> Product Liability\n66 -> Professional Malpractice\n67 -> Property Law &amp; Real Estate\n68 -> Public Utilities\n69 -> Remedies\n70 -> Sanctions\n71 -> Securities Law\n72 -> Sports Law\n73 -> Tax Law\n74 -> Tax-exempt Organizations\n75 -> Transportation\n76 -> Water Law\n77 -> White Collar Crime\n78 -> Workers' Compensation"

In [3]:
lawcat=content.splitlines()
f.close()
lawcat

['1 -> Administrative Law',
 '2 -> Admiralty',
 '3 -> Agriculture',
 '4 -> Antitrust &amp; Trade Regulation',
 "5 -> Attorney's Fees",
 '6 -> Banking Law',
 '7 -> Bankruptcy Law',
 '8 -> Civil Procedure',
 '9 -> Civil Rights',
 '10 -> Class Actions',
 '11 -> Commercial Law',
 '12 -> Communications Law',
 '13 -> Constitutional Law',
 '14 -> Construction',
 '15 -> Consumer Protection Law',
 '16 -> Contracts',
 '17 -> Corp. Governance',
 '18 -> Corporation &amp; Enterprise Law',
 '19 -> Criminal Law &amp; Procedure',
 '20 -> Habeas Corpus',
 '21 -> Sentencing',
 '22 -> Cyberspace Law',
 '23 -> Debt Collection',
 '24 -> Dispute Resolution &amp; Arbitration',
 '25 -> Drugs &amp; Biotech',
 '31 -> ERISA',
 '26 -> Education Law',
 '27 -> Elder Law',
 '28 -> Elections',
 '29 -> Entertainment Law',
 '30 -> Environmental Law',
 '32 -> Ethics &amp; Disciplinary Code',
 '33 -> Ethics &amp; Professional Responsibility',
 '34 -> Evidence',
 '35 -> False Advertising',
 '36 -> Family Law',
 '37 -> Gaming Law',
 '38 -> Government Benefits',
 '39 -> Government Contracts',
 '40 -> Government Law',
 '41 -> Health Law',
 '42 -> Immigration Law',
 '43 -> Indian Law',
 '44 -> Injury &amp; Tort Law',
 '45 -> Insurance Law',
 '47 -> Copyright',
 '49 -> Trade Dress',
 '50 -> Trade Secrets',
 '51 -> Trademark',
 '52 -> International Law',
 '53 -> International Trade',
 '54 -> Judgment Enforcement',
 '55 -> Judges &amp; Judiciary',
 '56 -> Juvenile Law',
 '57 -> Labor &amp; Employment Law',
 '58 -> Landlord Tenant Law',
 '59 -> Legal Malpractice',
 '60 -> M&amp;A',
 '61 -> Media Law',
 '62 -> Military Law',
 '63 -> Oil and Gas Law',
 '64 -> Probate, Trusts &amp; Estates',
 '65 -> Product Liability',
 '66 -> Professional Malpractice',
 '67 -> Property Law &amp; Real Estate',
 '68 -> Public Utilities',
 '69 -> Remedies',
 '70 -> Sanctions',
 '71 -> Securities Law',
 '72 -> Sports Law',
 '73 -> Tax Law',
 '74 -> Tax-exempt Organizations',
 '75 -> Transportation',
 '76 -> Water Law',
 '77 -> White Collar Crime',
 "78 -> Workers' Compensation"]

In [4]:
catagories=[]
for itemset in lawcat:
    meepset=itemset.partition('->')
    print(meepset)
    print(meepset[2])
    catagories.append(meepset)

('1 ', '->', ' Administrative Law')
 Administrative Law
('2 ', '->', ' Admiralty')
 Admiralty
('3 ', '->', ' Agriculture')
 Agriculture
('4 ', '->', ' Antitrust &amp; Trade Regulation')
 Antitrust &amp; Trade Regulation
('5 ', '->', " Attorney's Fees")
 Attorney's Fees
('6 ', '->', ' Banking Law')
 Banking Law
('7 ', '->', ' Bankruptcy Law')
 Bankruptcy Law
('8 ', '->', ' Civil Procedure')
 Civil Procedure
('9 ', '->', ' Civil Rights')
 Civil Rights
('10 ', '->', ' Class Actions')
 Class Actions
('11 ', '->', ' Commercial Law')
 Commercial Law
('12 ', '->', ' Communications Law')
 Communications Law
('13 ', '->', ' Constitutional Law')
 Constitutional Law
('14 ', '->', ' Construction')
 Construction
('15 ', '->', ' Consumer Protection Law')
 Consumer Protection Law
('16 ', '->', ' Contracts')
 Contracts
('17 ', '->', ' Corp. Governance')
 Corp. Governance
('18 ', '->', ' Corporation &amp; Enterprise Law')
 Corporation &amp; Enterprise Law
('19 ', '->', ' Criminal Law &amp; Procedure')
 Criminal Law &amp; Procedure
('20 ', '->', ' Habeas Corpus')
 Habeas Corpus
('21 ', '->', ' Sentencing')
 Sentencing
('22 ', '->', ' Cyberspace Law')
 Cyberspace Law
('23 ', '->', ' Debt Collection')
 Debt Collection
('24 ', '->', ' Dispute Resolution &amp; Arbitration')
 Dispute Resolution &amp; Arbitration
('25 ', '->', ' Drugs &amp; Biotech')
 Drugs &amp; Biotech
('31 ', '->', ' ERISA')
 ERISA
('26 ', '->', ' Education Law')
 Education Law
('27 ', '->', ' Elder Law')
 Elder Law
('28 ', '->', ' Elections')
 Elections
('29 ', '->', ' Entertainment Law')
 Entertainment Law
('30 ', '->', ' Environmental Law')
 Environmental Law
('32 ', '->', ' Ethics &amp; Disciplinary Code')
 Ethics &amp; Disciplinary Code
('33 ', '->', ' Ethics &amp; Professional Responsibility')
 Ethics &amp; Professional Responsibility
('34 ', '->', ' Evidence')
 Evidence
('35 ', '->', ' False Advertising')
 False Advertising
('36 ', '->', ' Family Law')
 Family Law
('37 ', '->', ' Gaming Law')
 Gaming Law
('38 ', '->', ' Government Benefits')
 Government Benefits
('39 ', '->', ' Government Contracts')
 Government Contracts
('40 ', '->', ' Government Law')
 Government Law
('41 ', '->', ' Health Law')
 Health Law
('42 ', '->', ' Immigration Law')
 Immigration Law
('43 ', '->', ' Indian Law')
 Indian Law
('44 ', '->', ' Injury &amp; Tort Law')
 Injury &amp; Tort Law
('45 ', '->', ' Insurance Law')
 Insurance Law
('47 ', '->', ' Copyright')
 Copyright
('49 ', '->', ' Trade Dress')
 Trade Dress
('50 ', '->', ' Trade Secrets')
 Trade Secrets
('51 ', '->', ' Trademark')
 Trademark
('52 ', '->', ' International Law')
 International Law
('53 ', '->', ' International Trade')
 International Trade
('54 ', '->', ' Judgment Enforcement')
 Judgment Enforcement
('55 ', '->', ' Judges &amp; Judiciary')
 Judges &amp; Judiciary
('56 ', '->', ' Juvenile Law')
 Juvenile Law
('57 ', '->', ' Labor &amp; Employment Law')
 Labor &amp; Employment Law
('58 ', '->', ' Landlord Tenant Law')
 Landlord Tenant Law
('59 ', '->', ' Legal Malpractice')
 Legal Malpractice
('60 ', '->', ' M&amp;A')
 M&amp;A
('61 ', '->', ' Media Law')
 Media Law
('62 ', '->', ' Military Law')
 Military Law
('63 ', '->', ' Oil and Gas Law')
 Oil and Gas Law
('64 ', '->', ' Probate, Trusts &amp; Estates')
 Probate, Trusts &amp; Estates
('65 ', '->', ' Product Liability')
 Product Liability
('66 ', '->', ' Professional Malpractice')
 Professional Malpractice
('67 ', '->', ' Property Law &amp; Real Estate')
 Property Law &amp; Real Estate
('68 ', '->', ' Public Utilities')
 Public Utilities
('69 ', '->', ' Remedies')
 Remedies
('70 ', '->', ' Sanctions')
 Sanctions
('71 ', '->', ' Securities Law')
 Securities Law
('72 ', '->', ' Sports Law')
 Sports Law
('73 ', '->', ' Tax Law')
 Tax Law
('74 ', '->', ' Tax-exempt Organizations')
 Tax-exempt Organizations
('75 ', '->', ' Transportation')
 Transportation
('76 ', '->', ' Water Law')
 Water Law
('77 ', '->', ' White Collar Crime')
 White Collar Crime
('78 ', '->', " Workers' Compensation")
 Workers' Compensation

In [21]:
catagories

[('1 ', '->', ' Administrative Law'),
 ('2 ', '->', ' Admiralty'),
 ('3 ', '->', ' Agriculture'),
 ('4 ', '->', ' Antitrust &amp; Trade Regulation'),
 ('5 ', '->', " Attorney's Fees"),
 ('6 ', '->', ' Banking Law'),
 ('7 ', '->', ' Bankruptcy Law'),
 ('8 ', '->', ' Civil Procedure'),
 ('9 ', '->', ' Civil Rights'),
 ('10 ', '->', ' Class Actions'),
 ('11 ', '->', ' Commercial Law'),
 ('12 ', '->', ' Communications Law'),
 ('13 ', '->', ' Constitutional Law'),
 ('14 ', '->', ' Construction'),
 ('15 ', '->', ' Consumer Protection Law'),
 ('16 ', '->', ' Contracts'),
 ('17 ', '->', ' Corp. Governance'),
 ('18 ', '->', ' Corporation &amp; Enterprise Law'),
 ('19 ', '->', ' Criminal Law &amp; Procedure'),
 ('20 ', '->', ' Habeas Corpus'),
 ('21 ', '->', ' Sentencing'),
 ('22 ', '->', ' Cyberspace Law'),
 ('23 ', '->', ' Debt Collection'),
 ('24 ', '->', ' Dispute Resolution &amp; Arbitration'),
 ('25 ', '->', ' Drugs &amp; Biotech'),
 ('31 ', '->', ' ERISA'),
 ('26 ', '->', ' Education Law'),
 ('27 ', '->', ' Elder Law'),
 ('28 ', '->', ' Elections'),
 ('29 ', '->', ' Entertainment Law'),
 ('30 ', '->', ' Environmental Law'),
 ('32 ', '->', ' Ethics &amp; Disciplinary Code'),
 ('33 ', '->', ' Ethics &amp; Professional Responsibility'),
 ('34 ', '->', ' Evidence'),
 ('35 ', '->', ' False Advertising'),
 ('36 ', '->', ' Family Law'),
 ('37 ', '->', ' Gaming Law'),
 ('38 ', '->', ' Government Benefits'),
 ('39 ', '->', ' Government Contracts'),
 ('40 ', '->', ' Government Law'),
 ('41 ', '->', ' Health Law'),
 ('42 ', '->', ' Immigration Law'),
 ('43 ', '->', ' Indian Law'),
 ('44 ', '->', ' Injury &amp; Tort Law'),
 ('45 ', '->', ' Insurance Law'),
 ('47 ', '->', ' Copyright'),
 ('49 ', '->', ' Trade Dress'),
 ('50 ', '->', ' Trade Secrets'),
 ('51 ', '->', ' Trademark'),
 ('52 ', '->', ' International Law'),
 ('53 ', '->', ' International Trade'),
 ('54 ', '->', ' Judgment Enforcement'),
 ('55 ', '->', ' Judges &amp; Judiciary'),
 ('56 ', '->', ' Juvenile Law'),
 ('57 ', '->', ' Labor &amp; Employment Law'),
 ('58 ', '->', ' Landlord Tenant Law'),
 ('59 ', '->', ' Legal Malpractice'),
 ('60 ', '->', ' M&amp;A'),
 ('61 ', '->', ' Media Law'),
 ('62 ', '->', ' Military Law'),
 ('63 ', '->', ' Oil and Gas Law'),
 ('64 ', '->', ' Probate, Trusts &amp; Estates'),
 ('65 ', '->', ' Product Liability'),
 ('66 ', '->', ' Professional Malpractice'),
 ('67 ', '->', ' Property Law &amp; Real Estate'),
 ('68 ', '->', ' Public Utilities'),
 ('69 ', '->', ' Remedies'),
 ('70 ', '->', ' Sanctions'),
 ('71 ', '->', ' Securities Law'),
 ('72 ', '->', ' Sports Law'),
 ('73 ', '->', ' Tax Law'),
 ('74 ', '->', ' Tax-exempt Organizations'),
 ('75 ', '->', ' Transportation'),
 ('76 ', '->', ' Water Law'),
 ('77 ', '->', ' White Collar Crime'),
 ('78 ', '->', " Workers' Compensation")]

In [5]:
data=pd.DataFrame(columns=['case_text','case_type'])

In [6]:
main_directory=os.getcwd()

pathToText='raw_cases\\raw_cases'

In [7]:
path=os.path.join(main_directory,pathToText)

In [8]:
masterpath=os.listdir(path)

In [9]:
counterfordocuments=1

for folder in masterpath[:-1]:
    subfile=os.listdir(os.path.join(path,folder))
    for rawtext in subfile:
        with open(os.path.join(path,folder)+'/' +rawtext,'r',encoding='utf-8') as f:
            content=f.read()
            vardict=pd.DataFrame({'case_text':content,'case_type':folder},index=[counterfordocuments])
            data=data.append(vardict)
            counterfordocuments+= 1

# remap numbers to text

In [35]:
law_cat_map={}
for item in catagories:
    law_cat_map[item[0].strip()]=item[2]

In [36]:
law_cat_map

{'1': ' Administrative Law',
 '2': ' Admiralty',
 '3': ' Agriculture',
 '4': ' Antitrust &amp; Trade Regulation',
 '5': " Attorney's Fees",
 '6': ' Banking Law',
 '7': ' Bankruptcy Law',
 '8': ' Civil Procedure',
 '9': ' Civil Rights',
 '10': ' Class Actions',
 '11': ' Commercial Law',
 '12': ' Communications Law',
 '13': ' Constitutional Law',
 '14': ' Construction',
 '15': ' Consumer Protection Law',
 '16': ' Contracts',
 '17': ' Corp. Governance',
 '18': ' Corporation &amp; Enterprise Law',
 '19': ' Criminal Law &amp; Procedure',
 '20': ' Habeas Corpus',
 '21': ' Sentencing',
 '22': ' Cyberspace Law',
 '23': ' Debt Collection',
 '24': ' Dispute Resolution &amp; Arbitration',
 '25': ' Drugs &amp; Biotech',
 '31': ' ERISA',
 '26': ' Education Law',
 '27': ' Elder Law',
 '28': ' Elections',
 '29': ' Entertainment Law',
 '30': ' Environmental Law',
 '32': ' Ethics &amp; Disciplinary Code',
 '33': ' Ethics &amp; Professional Responsibility',
 '34': ' Evidence',
 '35': ' False Advertising',
 '36': ' Family Law',
 '37': ' Gaming Law',
 '38': ' Government Benefits',
 '39': ' Government Contracts',
 '40': ' Government Law',
 '41': ' Health Law',
 '42': ' Immigration Law',
 '43': ' Indian Law',
 '44': ' Injury &amp; Tort Law',
 '45': ' Insurance Law',
 '47': ' Copyright',
 '49': ' Trade Dress',
 '50': ' Trade Secrets',
 '51': ' Trademark',
 '52': ' International Law',
 '53': ' International Trade',
 '54': ' Judgment Enforcement',
 '55': ' Judges &amp; Judiciary',
 '56': ' Juvenile Law',
 '57': ' Labor &amp; Employment Law',
 '58': ' Landlord Tenant Law',
 '59': ' Legal Malpractice',
 '60': ' M&amp;A',
 '61': ' Media Law',
 '62': ' Military Law',
 '63': ' Oil and Gas Law',
 '64': ' Probate, Trusts &amp; Estates',
 '65': ' Product Liability',
 '66': ' Professional Malpractice',
 '67': ' Property Law &amp; Real Estate',
 '68': ' Public Utilities',
 '69': ' Remedies',
 '70': ' Sanctions',
 '71': ' Securities Law',
 '72': ' Sports Law',
 '73': ' Tax Law',
 '74': ' Tax-exempt Organizations',
 '75': ' Transportation',
 '76': ' Water Law',
 '77': ' White Collar Crime',
 '78': " Workers' Compensation"}

In [39]:
law_type_df=data.replace({'case_type':law_cat_map})

In [40]:
law_type_df

                                               case_text            case_type
1      Petitioner Jhonatan Acosta (“Acosta”) petition...   Administrative Law
2      OPINION\nAnthony Araujo filed a complaint in t...   Administrative Law
3      OPINION\nRobert Zimmerman was riding his motor...   Administrative Law
4      OPINION\nThis case returns to us after the Sup...   Administrative Law
5      OPINION OF THE COURT\nHaddrick Byrd, a prisone...   Administrative Law
...                                                  ...                  ...
38285  The parties-who agree on little else-mutually ...      Civil Procedure
38286  This case involves the power of a district cou...      Civil Procedure
38287  Non-party appellants Stone & Webster Engineeri...      Civil Procedure
38288  On October 8, 1999, plaintiff-appellant José A...      Civil Procedure
38289  Under the authority of the Magnuson-Stevens Ac...      Civil Procedure

[38289 rows x 2 columns]

# most common words by law type list

# check point

In [10]:
data.case_type.value_counts()

42    2332
45    1569
20    1511
41    1455
36    1203
      ...
74      74
55      65
59      61
60      52
49      22
Name: case_type, Length: 75, dtype: int64

In [18]:
for classcount in data.case_type.value_counts():
    print(classcount)

2332
1569
1511
1455
1203
1059
1053
1034
1032
1024
1000
991
988
936
912
883
864
836
771
709
705
701
642
621
574
567
544
544
534
505
405
388
386
375
360
358
353
344
344
340
338
336
310
306
283
280
278
275
271
256
252
252
236
236
216
204
200
188
182
180
177
151
146
146
121
100
91
90
83
79
74
65
61
52
22

In [11]:
textdata=data['case_text']
target = data['case_type']

In [12]:
textdata

1        Petitioner Jhonatan Acosta (“Acosta”) petition...
2        OPINION\nAnthony Araujo filed a complaint in t...
3        OPINION\nRobert Zimmerman was riding his motor...
4        OPINION\nThis case returns to us after the Sup...
5        OPINION OF THE COURT\nHaddrick Byrd, a prisone...
                               ...
38285    The parties-who agree on little else-mutually ...
38286    This case involves the power of a district cou...
38287    Non-party appellants Stone & Webster Engineeri...
38288    On October 8, 1999, plaintiff-appellant José A...
38289    Under the authority of the Magnuson-Stevens Ac...
Name: case_text, Length: 38289, dtype: object

In [20]:
data.head()

                                           case_text case_type
1  Petitioner Jhonatan Acosta (“Acosta”) petition...         1
2  OPINION\nAnthony Araujo filed a complaint in t...         1
3  OPINION\nRobert Zimmerman was riding his motor...         1
4  OPINION\nThis case returns to us after the Sup...         1
5  OPINION OF THE COURT\nHaddrick Byrd, a prisone...         1

# break up for relevant information

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
text_tf = tf.fit_transform(data['case_text'])

text_tf_tfigf=pd.DataFrame(text_tf.todense(),columns = tf.get_feature_names(), dtype='int8')

,00,000,0000,000000,000000000001,0000000000564,0000000010,0000001,0000006000,0000006548,...,λd,μbga,μbgabga,μg,μgh,μm,μs,μw,ρς,τϕ
0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38284,0.0,0.005330,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38285,0.0,0.009676,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38286,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38287,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38288,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
relevant = []
for word in text_tf_tfigf.columns:
    if text_tf_tfigf[word].mean() > 0.0001:
        relevant.append(text_tf_tfigf[word])
len(relevant)

NameError: name 'text_tf_tfigf' is not defined